---
title: "Survey Methodology"
author: "SW"
date: Last updated on `r Sys.Date()`
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Survey Methodology

* Here is a sample of survey methodology: [Thematic Household Survey Report No. 84 - Explanatory Notes](https://stevenkhwun.github.io/testrepo/Survey_Methodology/THS84_Explanatory Notes.pdf)

* Key terms
  * [Coefficient of variation](https://en.wikipedia.org/wiki/Coefficient_of_variation)
  
  * [Standard deviation vs standard error](https://library.soton.ac.uk/variance-standard-deviation-and-standard-error#:~:text=Standard%20deviation%20is%20used%20to,using%20software%20than%20by%20hand.)

```{r}
# To calculate the variance and standard deviation of the above dataset in R, we can create
# a variable for the data and then calculate the variance and standard deviation with the 
# 'var' and 'sd' functions respectively:
dataset <- c(7, 12, 5, 18, 5, 9, 10, 9, 12, 8, 12, 16)
var(dataset)
sd(dataset)
```

```{r}
# To find the standard error, you can define your own function to be simply the standard
# deviation divided by the square root of n and apply that function to the dataset:
standard.error <- function(x) sd(x)/sqrt(length(x))
standard.error(dataset)
```
